class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Purnima',
      'todays_panchang': "Today's Panchang",
      'sunrise': 'Sunrise',
      'sunset': 'Sunset',
      'moonrise': 'Moonrise',
      'moonset': 'Moonset',
      'tithi': 'Tithi',
      'vara': 'Vara',
      'nakshatra': 'Nakshatra',
      'yoga': 'Yoga',
      'karana': 'Karana',
      'ends': 'Ends',
      'unknown': 'Unknown',
      'chart_input_title': 'Birth Chart',
      'place_name': 'Place Name',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'date': 'Date',
      'time': 'Time',
      'generate_chart': 'Generate Chart',
      'your_chart': 'Your Chart',
      'details': 'Details',
      'house': 'House',
      'settings': 'Settings',
      'language': 'Language',
      'change_location': 'Change Location',
      'use_current_location': 'Use Current Location',
      'cancel': 'Cancel',
      'set': 'Set',
      'required': 'Required',
      'error': 'Error',
      'retry': 'Retry',
      'save': 'Save',
      'no_data': 'No data available',
      'nav_panchang': 'Panchang',
      'nav_chart': 'Chart',
      'shukla': 'Shukla',
      'krishna': 'Krishna',
      'tithi_1': 'Prathama',
      'tithi_2': 'Dwitiya',
      'tithi_3': 'Tritiya',
      'tithi_4': 'Chaturthi',
      'tithi_5': 'Panchami',
      'tithi_6': 'Shashthi',
      'tithi_7': 'Saptami',
      'tithi_8': 'Ashtami',
      'tithi_9': 'Navami',
      'tithi_10': 'Dashami',
      'tithi_11': 'Ekadashi',
      'tithi_12': 'Dwadashi',
      'tithi_13': 'Trayodashi',
      'tithi_14': 'Chaturdashi',
      'tithi_15': 'Purnima',
      'tithi_30': 'Amavasya',
      'nav_dasa': 'Dasa',
      'nav_muhurta': 'Muhurta',
      'choghadiya': 'Choghadiya',
      'hora': 'Hora',
      'rahu_kalam': 'Rahu Kalam',
      'yamagandam': 'Yamagandam',
      'gulika_kalam': 'Gulika Kalam',
      'day': 'Day',
      'night': 'Night',
      'good': 'Good',
      'bad': 'Bad',
      'neutral': 'Neutral',
      // Manual Location Toggle
      'use_manual_coords': 'Enter coordinates manually', // Add this key
      'location_not_available_for_muhurta': 'Location not available for Muhurta. Please set your location in settings or Panchang tab.',
      // Choghadiya Names
      'udveg': 'Udveg',
      'amrit': 'Amrit',
      'rog': 'Rog',
      'labh': 'Labh',
      'shubh': 'Shubh',
      'char': 'Char',
      'kal': 'Kal',
      'cal': 'Chal', // Variation
      'theme': 'Theme',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System Default',
    },
    'hi': {
      'app_title': 'पूर्णिमा',
      'todays_panchang': 'आज का पंचांग',
      'nav_panchang': 'पंचांग',
      'nav_chart': 'कुंडली',
      'sunrise': 'सूर्योदय',
      'sunset': 'सूर्यास्त',
      'moonrise': 'चंद्रोदय',
      'moonset': 'चंद्रास्त',
      'tithi': 'तिथि',
      'vara': 'वार',
      'nakshatra': 'नक्षत्र',
      'yoga': 'योग',
      'karana': 'करण',
      'ends': 'समाप्त',
      'unknown': 'अज्ञात',
      'chart_input_title': 'जन्म कुंडली',
      'place_name': 'स्थान का नाम',
      'latitude': 'अक्षांश',
      'longitude': 'देशांतर',
      'date': 'दिनांक',
      'time': 'समय',
      'generate_chart': 'कुंडली बनाएं',
      'your_chart': 'आपकी कुंडली',
      'details': 'विवरण',
      'house': 'भाव',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'change_location': 'स्थान बदलें',
      'use_current_location': 'वर्तमान स्थान का उपयोग करें',
      'cancel': 'रद्द करें',
      'set': 'सेट करें',
      'required': 'आवश्यक है',
      'error': 'त्रुटि',
      'retry': 'पुनः प्रयास करें',
      'save': 'सहेजें',
      'no_data': 'कोई डेटा उपलब्ध नहीं है',
      'shukla': 'शुक्ल',
      'krishna': 'कृष्ण',
      'tithi_1': 'प्रथमा',
      'tithi_2': 'द्वितीया',
      'tithi_3': 'तृतीया',
      'tithi_4': 'चतुर्थी',
      'tithi_5': 'पंचमी',
      'tithi_6': 'षष्ठी',
      'tithi_7': 'सप्तमी',
      'tithi_8': 'अष्टमी',
      'tithi_9': 'नवमी',
      'tithi_10': 'दशमी',
      'tithi_11': 'एकादशी',
      'tithi_12': 'द्वादशी',
      'tithi_13': 'त्रयोदशी',
      'tithi_14': 'चतुर्दशी',
      'tithi_15': 'पूर्णिमा',
      'tithi_30': 'अमावस्या',
      'nav_dasa': 'दशा',
      'nav_muhurta': 'मुहूर्त',
      'choghadiya': 'चौघड़िया',
      'hora': 'होरा',
      'rahu_kalam': 'राहु काल',
      'yamagandam': 'यमगंडम',
      'gulika_kalam': 'गुलिक काल',
      'day': 'दिन',
      'night': 'रात',
      'good': 'शुभ',
      'bad': 'अशुभ',
      'neutral': 'सामान्य',
      'udveg': 'उद्वेग',
      'amrit': 'अमृत',
      'rog': 'रोग',
      'labh': 'लाभ',
      'shubh': 'शुभ',
      'char': 'चर',
      'kal': 'काल',
      'cal': 'चल',
    },
    'te': {
      'app_title': 'పూర్ణిమ',
      'todays_panchang': 'నేటి పంచాంగం',
      'sunrise': 'సూర్యోదయం',
      'sunset': 'సూర్యాస్తమయం',
      'moonrise': 'చంద్రోదయం',
      'moonset': 'చంద్రాస్తమయం',
      'tithi': 'తిథి',
      'vara': 'వారము',
      'nakshatra': 'నక్షత్రం',
      'yoga': 'యోగం',
      'karana': 'కరణం',
      'ends': 'ముగింపు',
      'unknown': 'తెలియదు',
      'chart_input_title': 'జన్మ కుండలి',
      'place_name': 'ప్రాంతం పేరు',
      'latitude': 'అక్షాంశం',
      'longitude': 'రేఖాంశం',
      'date': 'తేదీ',
      'time': 'సమయం',
      'generate_chart': 'కుండలిని సృష్టించండి',
      'your_chart': 'మీ కుండలి',
      'details': 'వివరాలు',
      'house': 'భావం',
      'settings': 'అమరికలు',
      'language': 'భాష',
      'change_location': 'ప్రాంతాన్ని మార్చండి',
      'use_current_location': 'ప్రస్తుత ప్రాంతాన్ని ఉపయోగించండి',
      'cancel': 'రద్దు చేయండి',
      'set': 'అమర్చు',
      'required': 'అవసరం',
      'error': 'లోపం',
      'retry': 'మళ్ళీ ప్రయత్నించండి',
      'save': 'సేవ్',
      'no_data': 'సమాచారం అందుబాటులో లేదు',
      'nav_panchang': 'పంచాంగం',
      'nav_chart': 'కుండలి',
      'shukla': 'శుక్ల',
      'krishna': 'కృష్ణ',
      'tithi_1': 'పాడ్యమి',
      'tithi_2': 'విదియ',
      'tithi_3': 'తదియ',
      'tithi_4': 'చవితి',
      'tithi_5': 'పంచమి',
      'tithi_6': 'షష్ఠి',
      'tithi_7': 'సప్తమి',
      'tithi_8': 'అష్టమి',
      'tithi_9': 'నవమి',
      'tithi_10': 'దశమి',
      'tithi_11': 'ఏకాదశి',
      'tithi_12': 'ద్వాదశి',
      'tithi_13': 'త్రయోదశి',
      'tithi_14': 'చతుర్దశి',
      'tithi_15': 'పౌర్ణమి',
      'tithi_30': 'అమావాస్య',
      'nav_dasa': 'దశ',
      'nav_muhurta': 'ముహూర్తం',
      'choghadiya': 'చోఘడియా',
      'hora': 'హోరా',
      'rahu_kalam': 'రాహు కాలం',
      'yamagandam': 'యమగండం',
      'gulika_kalam': 'గుళిక కాలం',
      'day': 'పగలు',
      'night': 'రాత్రి',
      'good': 'శుభ',
      'bad': 'అశుభ',
      'neutral': 'సాధారణ',
      'udveg': 'ఉద్వేగ',
      'amrit': 'అమృత',
      'rog': 'రోగ',
      'labh': 'లాభ',
      'shubh': 'శుభ',
      'char': 'చర',
      'kal': 'కాల',
      'cal': 'చల',
    },
    'sa': {
      'app_title': 'पूर्णिमा',
      'todays_panchang': 'अद्यतन पञ्चाङ्गम्',
      'nav_panchang': 'पञ्चाङ्गम्',
      'nav_chart': 'कुण्डली',
      'sunrise': 'सूर्योदयः',
      'sunset': 'सूर्यास्तः',
      'moonrise': 'चन्द्रोदयः',
      'moonset': 'चन्द्रास्तः',
      'tithi': 'तिथिः',
      'vara': 'वासरः',
      'nakshatra': 'नक्षत्रम्',
      'yoga': 'योगः',
      'karana': 'करणम्',
      'ends': 'समाप्तिः',
      'unknown': 'अज्ञातम्',
      'chart_input_title': 'जन्मकुण्डली',
      'place_name': 'स्थाननाम',
      'latitude': 'अक्षांशः',
      'longitude': 'देशान्तरः',
      'date': 'दिनाङ्कः',
      'time': 'समयः',
      'generate_chart': 'कुण्डलीं रचयतु',
      'your_chart': 'भवतः कुण्डली',
      'details': 'विवरणम्',
      'house': 'भावः',
      'settings': 'विन्यासाः',
      'language': 'भाषा',
      'change_location': 'स्थानं परिवर्तयतु',
      'use_current_location': 'वर्तमानस्थानं उपयुज्यताम्',
      'cancel': 'निरस्तम्',
      'set': 'स्थापयतु',
      'required': 'आवश्यकम्',
      'error': 'दोषः',
      'retry': 'पुनः प्रयतताम्',
      'save': 'रक्षतु',
      'no_data': 'दत्तांशः न उपलब्धः',
      'shukla': 'शुक्ल',
      'krishna': 'कृष्ण',
      'tithi_1': 'प्रथमा',
      'tithi_2': 'द्वितीया',
      'tithi_3': 'तृतीया',
      'tithi_4': 'चतुर्थी',
      'tithi_5': 'पञ्चमी',
      'tithi_6': 'षष्ठी',
      'tithi_7': 'सप्तमी',
      'tithi_8': 'अष्टमी',
      'tithi_9': 'नवमी',
      'tithi_10': 'दशमी',
      'tithi_11': 'एकादशी',
      'tithi_12': 'द्वादशी',
      'tithi_13': 'त्रयोदशी',
      'tithi_14': 'चतुर्दशी',
      'tithi_15': 'पूर्णिमा',
      'tithi_30': 'अमावस्या',
      'nav_dasa': 'दशा',
      'nav_muhurta': 'मुहूर्तः',
      'choghadiya': 'चोघडिया',
      'hora': 'होरा',
      'rahu_kalam': 'राहुकालः',
      'yamagandam': 'यमगण्डम्',
      'gulika_kalam': 'गुलिककालः',
      'day': 'दिवा',
      'night': 'रात्रि',
      'good': 'शुभम्',
      'bad': 'अशुभम्',
      'neutral': 'सामान्यम्',
      'udveg': 'उद्वेगः',
      'amrit': 'अमृतम्',
      'rog': 'रोगः',
      'labh': 'लाभः',
      'shubh': 'शुभम्',
      'char': 'चरः',
      'kal': 'कालः',
      'cal': 'चलः',
    },
    'ta': {
      'app_title': 'பூர்ணிமா',
      'todays_panchang': 'இன்றைய பஞ்சாங்கம்',
      'sunrise': 'சூரிய உதயம்',
      'sunset': 'சூரிய அஸ்தமனம்',
      'moonrise': 'சந்திர உதயம்',
      'moonset': 'சந்திர அஸ்தமனம்',
      'tithi': 'திதி',
      'vara': 'வாரம்',
      'nakshatra': 'நட்சத்திரம்',
      'yoga': 'யோகம்',
      'karana': 'கரணம்',
      'ends': 'முடிவு',
      'unknown': 'தெரியவில்லை',
      'chart_input_title': 'பிறப்பு ஜாதகம்',
      'place_name': 'இடத்தின் பெயர்',
      'latitude': 'அட்சரேகை',
      'longitude': 'தீர்க்கரேகை',
      'date': 'தேதி',
      'time': 'நேரம்',
      'generate_chart': 'ஜாதகத்தை உருவாக்கு',
      'your_chart': 'உங்கள் ஜாதகம்',
      'details': 'விவரங்கள்',
      'house': 'பாவம்',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'change_location': 'இடத்தை மாற்றவும்',
      'use_current_location': 'தற்போதைய இடத்தைப் பயன்படுத்தவும்',
      'cancel': 'ரத்துசெய்',
      'set': 'அமை',
      'required': 'தேவை',
      'save': 'சேமி',
      'nav_panchang': 'பஞ்சாங்கம்',
      'nav_chart': 'ஜாதகம்',
      'shukla': 'சுக்ல',
      'krishna': 'கிருஷ்ண',
      'tithi_1': 'பிரதமை',
      'tithi_2': 'துவிதியை',
      'tithi_3': 'திருதியை',
      'tithi_4': 'சதுர்த்தி',
      'tithi_5': 'பஞ்சமி',
      'tithi_6': 'சஷ்டி',
      'tithi_7': 'சப்தமி',
      'tithi_8': 'அஷ்டமி',
      'tithi_9': 'நவமி',
      'tithi_10': 'தசமி',
      'tithi_11': 'ஏகாதசி',
      'tithi_12': 'துவாதசி',
      'tithi_13': 'திரயோதசி',
      'tithi_14': 'சதுர்த்தசி',
      'tithi_15': 'பௌர்ணமி',
      'tithi_30': 'அமாவாசை',
      'nav_dasa': 'திசை',
      'nav_muhurta': 'முகூர்த்தம்',
      'choghadiya': 'சோகடியா',
      'hora': 'ஹோரை',
      'rahu_kalam': 'ராகு காலம்',
      'yamagandam': 'எமகண்டம்',
      'gulika_kalam': 'குளிகை காலம்',
      'day': 'பகல்',
      'night': 'இரவு',
      'good': 'நல்லது',
      'bad': 'கெட்டது',
      'neutral': 'சாதாரண',
      'udveg': 'உத்வேகம்',
      'amrit': 'அமிர்தம்',
      'rog': 'ரோகம்',
      'labh': 'லாபம்',
      'shubh': 'சுபம்',
      'char': 'சரம்',
      'kal': 'காலம்',
      'cal': 'சலம்',
    },
    'kn': {
      'app_title': 'ಪೂರ್ಣಿಮಾ',
      'todays_panchang': 'ಇಂದಿನ ಪಂಚಾಂಗ',
      'nav_panchang': 'ಪಂಚಾಂಗ',
      'nav_chart': 'ಕುಂಡಲಿ',
      'sunrise': 'ಸೂರ್ಯೋದಯ',
      'sunset': 'ಸೂರ್ಯಾಸ್ತ',
      'moonrise': 'ಚಂದ್ರೋದಯ',
      'moonset': 'ಚಂದ್ರಾಸ್ತ',
      'tithi': 'ತಿಥಿ',
      'vara': 'ವಾರ',
      'nakshatra': 'ನಕ್ಷತ್ರ',
      'yoga': 'ಯೋಗ',
      'karana': 'ಕರಣ',
      'ends': 'ಮುಕ್ತಾಯ',
      'unknown': 'ಅಜ್ಞಾತ',
      'chart_input_title': 'ಜನ್ಮ ಕುಂಡಲಿ',
      'place_name': 'ಸ್ಥಳದ ಹೆಸರು',
      'latitude': 'ಅಕ್ಷಾಂಶ',
      'longitude': 'ರೇಖಾಂಶ',
      'date': 'ದಿನಾಂಕ',
      'time': 'ಸಮಯ',
      'generate_chart': 'ಕುಂಡಲಿಯನ್ನು ರಚಿಸಿ',
      'your_chart': 'ನಿಮ್ಮ ಕುಂಡಲಿ',
      'details': 'ವಿವರಗಳು',
      'house': 'ಭಾವ',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'language': 'ಭಾಷೆ',
      'change_location': 'ಸ್ಥಳವನ್ನು ಬದಲಾಯಿಸಿ',
      'use_current_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'set': 'ಹೊಂದಿಸಿ',
      'required': 'ಅಗತ್ಯವಿದೆ',
      'error': 'ದೋಷ',
      'retry': 'ಮತ್ತೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ',
      'save': 'ಉಳಿಸಿ',
      'no_data': 'ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ',
      'shukla': 'ಶುಕ್ಲ',
      'krishna': 'ಕೃಷ್ಣ',
      'tithi_1': 'ಪಾಡ್ಯ',
      'tithi_2': 'ಬಿದಿಗೆ',
      'tithi_3': 'ತದಿಗೆ',
      'tithi_4': 'ಚೌತಿ',
      'tithi_5': 'ಪಂಚಮಿ',
      'tithi_6': 'ಷಷ್ಠಿ',
      'tithi_7': 'ಸಪ್ತಮಿ',
      'tithi_8': 'ಅಷ್ಟಮಿ',
      'tithi_9': 'ನವಮಿ',
      'tithi_10': 'ದಶಮಿ',
      'tithi_11': 'ಏಕಾದಶಿ',
      'tithi_12': 'ದ್ವಾದಶಿ',
      'tithi_13': 'ತ್ರಯೋದಶಿ',
      'tithi_14': 'ಚತುರ್ದಶಿ',
      'tithi_15': 'ಹುಣ್ಣಿಮೆ',
      'tithi_30': 'ಅಮಾವಾಸ್ಯೆ',
      'nav_dasa': 'ದಶೆ',
      'nav_muhurta': 'ಮುಹೂರ್ತ',
      'choghadiya': 'ಚೋಗಡಿಯ',
      'hora': 'ಹೋರಾ',
      'rahu_kalam': 'ರಾಹು ಕಾಲ',
      'yamagandam': 'ಯಮಗಂಡ',
      'gulika_kalam': 'ಗುಳಿಕ ಕಾಲ',
      'day': 'ಹಗಲು',
      'night': 'ರಾತ್ರಿ',
      'good': 'ಶುಭ',
      'bad': 'ಅಶುಭ',
      'neutral': 'ಸಾಮಾನ್ಯ',
      'udveg': 'ಉದ್ವೇಗ',
      'amrit': 'ಅಮೃತ',
      'rog': 'ರೋಗ',
      'labh': 'ಲಾಭ',
      'shubh': 'ಶುಭ',
      'char': 'ಚರ',
      'kal': 'ಕಾಲ',
      'cal': 'ಚಲ',
    },
    'mr': { // Added Marathi support example if needed, or stick to existing languages
       // Assuming user meant "works only in english" implying existing translations might be missing for Muhurta keys in other languages.
       // I see keys like 'choghadiya', 'good', 'bad' ARE present in 'te', 'hi', 'ta', 'kn'.
       // Wait, I should verify if the API actually returns localized strings for "Udveg", "Amrit", etc?
       // The API returns "Udveg", "Amrit", etc as `name`. These are proper nouns but have specific meanings/translations.
       // Also the `nature` field returns "GOOD", "BAD", "NEUTRAL" which I am handling with lowercase keys.
       // BUT the Choghadiya NAMES themselves (Udveg, Labh, Char, etc.) are NOT localized in AppStrings.
       // I need to add keys for Choghadiya names to AppStrings.
    },
  };

  static String get(String key, String languageCode) {
    if (_localizedValues.containsKey(languageCode) && _localizedValues[languageCode]!.containsKey(key)) {
      return _localizedValues[languageCode]![key]!;
    }
    // Fallback to English
    if (_localizedValues['en']!.containsKey(key)) {
      return _localizedValues['en']![key]!;
    }
    // Final fallback: return the key itself so we don't crash
    return key; 
  }
}
